FROM pstk:latest

USER root
RUN apt install -y git libxslt1-dev libxslt1.1 libxml2 libxml2-dev 

USER postgres
WORKDIR /postxml
RUN git clone https://github.com/albaike/postxml .
# RUN git checkout afee9333596330dbb8eb62113ed264b0c4c7edbf

USER root
RUN apt remove -y git

COPY docker_pstk.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/docker_pstk.sh

EXPOSE 5432
COPY docker_postgres.sh /
RUN chmod +x /docker_postgres.sh

USER postgres

CMD ["bash", "/docker_postgres.sh"]