FROM pstk:latest

USER root
RUN apt install -y git libxslt1-dev libxslt1.1 libxml2 libxml2-dev 

USER postgres
WORKDIR /postxml
RUN git clone https://github.com/albaike/postxml .

USER root
RUN apt remove -y git

EXPOSE 5432

USER postgres
RUN echo 'export PSTK_ARGS="--extension --schema-path=postxml--1.0.sql /postxml test"' \
    >> ~/.env

CMD ["bash", "/docker_postgres.sh"]