name: Test package

on:
  push:
    branches:
      - master

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      environment: testing
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: install project dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --no-root
            
        - name: Install project binary
          run: |
            poetry install

        - name: Install Postgres-16
          run: |
            sudo apt install -y postgresql-common
            sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
            sudo apt install -y postgresql-16 postgresql-client-16

        - name: Remove Postgres-14
          run: |
            sudo apt remove -y postgresql-14 postgresql-client-14

        - name: Verify Postgres-16
          run: |
            sudo systemctl start postgresql
            sudo systemctl status postgresql

        - name: Install and test extension
          run: |
            git clone https://github.com/albaike/postxml
            cd postxml
            pstk --extension --schema-path=postxml--1.0.sql . test